trigger: none

pool:
  vmImage: ubuntu-latest

steps:
# 1) Instala Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js 20'

# 2) Limpa cache do Yarn e instala dependências com Yarn v1
- script: |
    npm install -g yarn@1
    echo "Yarn version:"
    yarn --version

    echo "Limpando cache do Yarn..."
    yarn cache clean

    echo "Instalando dependências..."
    yarn install --frozen-lockfile

    echo "Iniciando build do projeto..."
    yarn build
  displayName: 'Yarn clean, install & build'
  env:
    CI: true
    NEXT_DISABLE_FONT_DOWNLOAD: '1'
    NEXT_TELEMETRY_DISABLED: '1'

# 3) Deploy para Azure Static Web Apps (SSR/ISR)
- task: AzureStaticWebApp@0
  displayName: 'Deploy to Azure Static Web Apps'
  inputs:
    azure_static_web_apps_api_token: $(azure_static_web_apps_api_token)
    app_location: '/'        # raiz do repo
    output_location: '.next' # artefatos criados por "next build"
    api_location: ''         # deixe vazio se não usa funções
