trigger: none

pool:
  vmImage: ubuntu-latest

steps:
# 1) Instala Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js 20'

# 2) Instala Yarn v1 e faz build
- script: |
    npm install -g yarn@1
    yarn --version          # debug
    yarn install --frozen-lockfile
    yarn build              # cria .next/ para SSR
  displayName: 'yarn install & build'
  env:
    CI: true
    NEXT_DISABLE_FONT_DOWNLOAD: '1'   # mantém o bypass de fontes, se quiser
    NEXT_TELEMETRY_DISABLED: '1'

# 3) Deploy para Azure Static Web Apps (SSR/ISR)
- task: AzureStaticWebApp@0
  displayName: 'Deploy to Azure Static Web Apps'
  inputs:
    azure_static_web_apps_api_token: $(azure_static_web_apps_api_token)
    app_location: '/'        # raiz do repo
    output_location: '.next' # artefatos criados por "next build"
    api_location: ''         # deixe vazio se não usa funções
